version: '3'

services:
  serverless:
    build: 
      context: .
      # args: 
      #   - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      #   - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    stdin_open: true
    image: serverless
    working_dir: /app
    volumes:
      - .:/app
    container_name: serverless
